### PR TITLE
[682] Case-insensitive lookup of GitHub handle for role assignment

### LINKED ISSUE #682: Bug: github handle is case sensitive
To reproduce: add a coach to a team. their github username must be capitalised to match, or else the app saves it as blank.

### PR DESCRIPTION
**Pull request by carpodaster**
Fixes #682

### CODE REVIEW

File: spec/controllers/teams_controller_spec.rb [hunk 1]
```diff
@@ -146,30 +146,52 @@
...
+            expect {
+              patch :update, params: { id: team.to_param, team: valid_attributes }
+            }.to change { User.count }.by 1
+
+            expect(User.last.github_handle).to eql github_handle
+          end
+
+          it 'finds an existing user by case-insenstive github_handle' do
+            existing_user = create :user, github_handle: github_handle.upcase
+            expect {
```
Comment (F3PiX) [inline spec/controllers/teams_controller_spec.rb]: As I understand issue #682, the problem is with lowercase input. Does it make sense to add a spec with `github_handle.lowercase`?

Comment (carpodaster) [inline spec/controllers/teams_controller_spec.rb]: I just wanted to have a different case. I thought of adding a lambda `randomize_case` but decided against it. Do you think it would make the intention of the example more clear? If so, I'll add that.

File: spec/controllers/teams_controller_spec.rb [hunk 2]
```diff
@@ -146,30 +146,52 @@
...
+
+          it 'creates a new user from github_handle' do
+            expect {
+              patch :update, params: { id: team.to_param, team: valid_attributes }
+            }.to change { User.count }.by 1
+
+            expect(User.last.github_handle).to eql github_handle
+          end
+
+          it 'finds an existing user by case-insenstive github_handle' do
```
Comment (alicetragedy) [inline spec/controllers/teams_controller_spec.rb]: s/insenstive/insensitive

File: spec/controllers/teams_controller_spec.rb (hunk 1 above)
Comment (alicetragedy) [inline spec/controllers/teams_controller_spec.rb]: yeah, I think either randomizing or explicitly setting it to lowercase would make sense. +1 on Maud's suggestion.
