### PR TITLE
Fix/redirect after deleting user

### LINKED ISSUE #915: deleting a user redirects to a non-existing page
When you delete a user (either as an organiser or, I'm guessing, as a user trying to delete your own profile, if that's a possible use case), you get redirected to `/users` which does not exist anymore (i.e. visitor gets a 404). The visitor should probably get redirected to `/community` instead, which is the “new” user list page.

### PR DESCRIPTION
**Pull request by carpodaster**
Fixes #915 

* Fixes the redirect target
* Improves the naming of the named route for `/community` (i.e. `community_path` now)
* Logs out the current user if they just deleted themselves.

### CODE REVIEW

File: spec/controllers/users_controller_spec.rb [hunk 1]
```diff
@@ -165,20 +165,15 @@
...
-    end
+    before { sign_in user }
 
     context "its own profile" do
-      it "destroys the requested user" do
-        expect {
-          delete :destroy, params: { id: user.to_param }
-        }.to change(User, :count).by(-1)
-      end
+      it "destroys the requested user and redirects to /community" do
```
Comment (carpodaster) [inline spec/controllers/users_controller_spec.rb]: I know this violates the "one assertion per example" rule. But that's how I roll in controller/request/feature/functional tests because the setup of DB objects is too expensive to not reuse the existing setup.

Comment (F3PiX) [reply spec/controllers/users_controller_spec.rb]: I am totally convinced ;-) 
In our first Dev Sync we talked about moving from controller tests to request tests. Would that help in this case?

Comment (carpodaster) [reply spec/controllers/users_controller_spec.rb]: Not as long the "one assertion per example" mantra is still being held up; the test would look almost the same, only the test macros change a little. I did not rewrite this as a request spec (even though we decided to gradually move request specs in the first DevSync as you mentioned) since we already had an exisiting test and I think the move to request specs should be one big PR on its own.

**Comment by carpodaster** [comment]
@F3PiX I don't know much about Devise's magic tricks. What do you have in mind?

**Comment by ramonh** [comment]
Thanks @carpodaster ! Looks good to me, too!
